artifacts_root: artifacts
#This will create folder we can have folders and files will be used for project

#It will create a folder called data_ingestion under artifacts and bring the input zip file
data_ingestion:
  root_dir: artifacts/data_ingestion # In future if you are trying to modify anything out of these we can simply modify in this file. 
  # Hard coding directly inside the coding files will leads compliacations when editing
  source_URL: https://github.com/venkatshan707/DataSets/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model # Directory for saving base model
  base_model_path: artifacts/prepare_base_model/base_model.h5 # downloading v16 base model in the locationa and saving as it is.
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 # adding custom layer with base model downlaoded

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir # To view the track of model training
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras #To have checkpoints on model training. From one check point (after training some ephocs some checkpoints will be saved) we can resume traing as well